POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "ya2",
    "author": "Thirds",
    "url": "yourMoms",
    "userId": "68d6c3cb18e722e3ef1d898a"
}
###
GET http://localhost:3003/api/blogs
###
DELETE http://localhost:3003/api/blogs/68d5691a76f9b58f720672ec
###
PUT http://localhost:3003/api/blogs/68d57a8b1a77e4a330c0c0a7
Content-Type: application/json

{
    "title": "updated",
    "author": "New Author",
    "url": "http://your.mom",
    "likes": 345
}