POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "Superuser",
  "password": "NewPass"
}
###
GET http://localhost:3003/api/users
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "newTitle",
  "author": "Daniel",
  "url": "http://www.yeeeahhhh.com",
  "userId": "68d6c3cb18e722e3ef1d898a"
}
###
Get http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "NewPass"
}